USE_FUNCTION_BIG_DECIMAL =
SELECT SUM(1.1) BIG_DECIMAL_COL
FROM DAO_USERS

USE_FUNCTION_INTEGER =
SELECT SUM(100) INTEGER_COL
FROM DAO_USERS

USE_FUNCTION_LONG =
SELECT SUM(VERSION) LONG_COL
FROM DAO_USERS
